import { describe, expect, it } from 'vitest'
import { defaultState } from '../calc/defaults'
import { computeModel } from '../calc/model'
import { MAX_LINK_LENGTH, decodePlan, decodePlanArray, encodePlan, packPlan } from './share'
import { planFileContents } from './planFile'

const state = defaultState()

/** What the reader actually sees has to survive the trip; ids are regenerated by design. */
function stripIds<T extends { id: string }>(rows: T[]): Omit<T, 'id'>[] {
  return rows.map(({ id: _id, ...rest }) => rest)
}

function fingerprint(s: ReturnType<typeof defaultState>) {
  const r = (id: 'lean' | 'base' | 'aggressive') =>
    computeModel({ company: s.company, scenario: s.scenarios[id] })
  return {
    active: s.activeScenario,
    company: {
      ...s.company,
      founders: stripIds(s.company.founders),
      expenses: stripIds(s.company.expenses),
    },
    results: (['lean', 'base', 'aggressive'] as const).map((id) => {
      const m = r(id)
      return [
        m.burn.currentMonthlyBurn,
        m.capital.recommendedRaise,
        m.capital.plannedRaise,
        m.runway.withRaise,
        m.safe.totalSafeOwnership,
        m.safe.founderBlockAfter,
      ]
    }),
  }
}

describe('a plan in a link', () => {
  it('round-trips every number the reader can see', () => {
    const revived = decodePlan(encodePlan(state))
    expect(revived).not.toBeNull()
    expect(fingerprint(revived!)).toEqual(fingerprint(state))
  })

  it('round-trips an edited plan, including which scenario is open', () => {
    const edited = structuredClone(state)
    edited.activeScenario = 'aggressive'
    edited.company.currentCash = 275_000
    edited.company.founders[0].name = 'Ada'
    edited.company.founders[0].equityShare = 0.6
    edited.company.founders[1].equityShare = 0.4
    edited.scenarios.aggressive.optionPool = { currentPct: 0.05, newPct: 0.15 }
    edited.scenarios.aggressive.safe.discountRate = 0.2
    edited.scenarios.aggressive.investors[0].investment = 1_750_000
    edited.scenarios.lean.hires = [
      { id: 'x', role: 'Designer', headcount: 2, annualSalary: 140_000, startMonth: 7 },
    ]
    const revived = decodePlan(encodePlan(edited))!
    expect(revived.activeScenario).toBe('aggressive')
    expect(revived.company.currentCash).toBe(275_000)
    expect(revived.company.founders[0].name).toBe('Ada')
    expect(revived.scenarios.aggressive.optionPool).toEqual({ currentPct: 0.05, newPct: 0.15 })
    expect(revived.scenarios.aggressive.safe.discountRate).toBe(0.2)
    expect(revived.scenarios.lean.hires[0]).toMatchObject({ role: 'Designer', headcount: 2, startMonth: 7 })
    expect(fingerprint(revived)).toEqual(fingerprint(edited))
  })

  it('gives every revived row a fresh unique id', () => {
    const revived = decodePlan(encodePlan(state))!
    const ids = [
      ...revived.company.founders.map((f) => f.id),
      ...revived.company.expenses.map((e) => e.id),
      ...revived.scenarios.base.investors.map((i) => i.id),
      ...revived.scenarios.base.hires.map((h) => h.id),
    ]
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('stays short enough to paste', () => {
    expect(encodePlan(state).length).toBeLessThan(MAX_LINK_LENGTH)
  })

  it('is url-safe: no +, / or = to be mangled in transit', () => {
    expect(encodePlan(state)).toMatch(/^[A-Za-z0-9\-_]+$/)
  })
})

describe('a link is untrusted input', () => {
  it('returns null for anything that is not a plan', () => {
    for (const junk of ['', 'x', 'notbase64!!', btoa('{}'), btoa('[]'), btoa('null')]) {
      expect(decodePlan(junk)).toBeNull()
    }
  })

  it('refuses a payload from a future format instead of guessing at it', () => {
    const packed = packPlan(state)
    packed[0] = 99
    expect(decodePlanArray(packed)).toBeNull()
  })

  it('repairs a truncated plan rather than handing the engine holes', () => {
    const revived = decodePlanArray([1, 1, [0.25, 0], [], [], []])
    expect(revived).not.toBeNull()
    // Missing founders and scenarios fall back to the seed, so the app still runs.
    expect(revived!.company.founders).toEqual(state.company.founders)
    expect(revived!.scenarios.base.targetRunwayMonths).toBe(
      state.scenarios.base.targetRunwayMonths,
    )
  })

  it('survives wrong types in every slot', () => {
    const revived = decodePlanArray([
      1,
      'nope',
      'nope',
      [['x', 'y', 'z', {}], 42],
      [[[], null]],
      ['nope', [null, null, 'x', null, null, 'x', 'x'], {}],
    ])
    expect(revived).not.toBeNull()
    const model = computeModel({
      company: revived!.company,
      scenario: revived!.scenarios.base,
    })
    expect(Number.isFinite(model.capital.recommendedRaise)).toBe(true)
    expect(Number.isFinite(model.safe.totalSafeOwnership)).toBe(true)
  })

  it('caps a name long enough to wreck the layout', () => {
    const edited = structuredClone(state)
    edited.company.founders[0].name = 'A'.repeat(5_000)
    const revived = decodePlan(encodePlan(edited))!
    expect(revived.company.founders[0].name.length).toBe(60)
  })

  it('keeps markup as text, since it is only ever rendered as text', () => {
    const edited = structuredClone(state)
    edited.company.expenses[0].name = '<img src=x onerror=alert(1)>'
    const revived = decodePlan(encodePlan(edited))!
    expect(revived.company.expenses[0].name).toBe('<img src=x onerror=alert(1)>')
  })
})

describe('a plan in a file', () => {
  it('writes readable JSON that reads back to the same plan', () => {
    const contents = planFileContents(state)
    expect(contents).toContain('"plan"')
    const parsed = JSON.parse(contents) as { plan: unknown }
    expect(fingerprint(decodePlanArray(parsed.plan)!)).toEqual(fingerprint(state))
  })
})
